language: android
jdk: oraclejdk8
sudo: true

android:
  components:
  - tools
  - build-tools-25.0.0
  - android-25
  - platform-tools
  - extra-android-m2repository
  - extra-google-android-support
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-support

  licenses:
  - .+

before_install:
#  - echo y | sudo apt-get update
#  - echo y | sudo apt-get install openjdk-7-jre
#  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
#  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
#  - export JAVA_HOME=$JAVA8_HOME
  - chmod +x gradlew
script:
   - ./gradlew clean
   - ./gradlew build
