language: android
jdk: oraclejdk8
sudo: false

android:
  component:
  - build-tools-25.0.2
  - android-25
  - tools
  - platform-tools

script:
    - chmod +x ./gradlew
    - ./gradlew clean
    - ./gradlew build
