language: android
jdk: oraclejdk8
sudo: true

android:
  components:
  - tools
  - build-tools-25.0.0
  - android-25
  - platform-tools
  - extra-android-m2repository
  - extra-google-android-support
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-support
#add constraint
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - ./gradlew dependencies || true

before_script:
  - echo y | sudo apt-get update
  - echo y | sudo apt-get install openjdk-7-jre
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME
  - chmod +x gradlew

licenses:
  - android-sdk-license-.+
  - '.+'

script:
  - ./gradlew clean
  - ./gradlew build

