language: android
jdk: oraclejdk8
sudo: false

android:
  components:
  - tools
  - build-tools-25.0.2
  - android-25
  - platform-tools
  - extra-android-m2repository
  - extra-google-android-support

  licenses:
  - '.+'

before_install:
  - echo y | sudo apt-get update
  - echo y | sudo apt-get install openjdk-7-jre
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME
  - chmod +x gradlew
script:
   - ./gradlew clean
   - ./gradlew build
