language: android
jdk: oraclejdk8
sudo: false

android:
  component:
  - build-tools-25.0.2
  - android-25
  - tools
  - platform-tools

  licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

script:
    - chmod +x ./gradlew
    - ./gradlew clean
    - ./gradlew build
