language: android
jdk: oraclejdk8
sudo: true

android:
  components:
  - tools
  - build-tools-25.0.0
  - android-25
  - platform-tools
  - extra-android-m2repository
  - extra-google-android-support
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-support

<<<<<<< Updated upstream
  licenses:
  - .+

=======
>>>>>>> Stashed changes
before_install:
  - echo y | sudo apt-get update
  - echo y | sudo apt-get install openjdk-7-jre
  - echo y | android update sdk --no-ui --all --filter build-tools-25.0.0 | grep 'package installed'
  - echo y | android update sdk --no-ui --all --filter extra-android-m2repository | grep 'package installed'
  - echo y | android update sdk --no-ui --all --filter extra-google-m2repository | grep 'package installed'
  - echo y | android update sdk --no-ui --all --filter extra-google-google_play_services | grep 'package installed'
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME
  - chmod +x gradlew
script:
   - ./gradlew clean
   - ./gradlew build
